version: 2.1
jobs:
  build:
    docker:
      
    
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

      # Specify the version you desire here
      - image: circleci/php:7.3-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - run: echo "Hello World"# PHP CircleCI 2.0 configuration file

      
      # Download and cache dependencies
      
            # "composer.lock" can be used if it is committed to the repo
           
            # fallback to using the latest cache if no exact match is found
        

      